name: shart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.3
  flutter_image_slideshow: ^0.1.6
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/banner1.jpg
    - assets/bg.jpg
